
export interface ReceiptItem {
  id: string; // Unique ID generated by frontend or index
  scanId?: string; // ID to identify which receipt scan this item belongs to
  name: string;
  price: number;
  quantity: number;
  assignedTo: string[]; // Array of names
}

export interface ReceiptData {
  items: ReceiptItem[];
  subtotal: number;
  tax: number;
  tip: number;
  total: number;
  currency: string;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model' | 'system';
  text: string;
  timestamp: number;
}

export interface PersonSummary {
  name: string;
  items: { name: string; cost: number; quantity: number }[];
  subtotal: number;
  taxShare: number;
  tipShare: number;
  total: number;
}
